# Environment configuration properties
environment=local
BaseURL=https://automationexercise.com/
Port=8080
apiEndpoint=http://localhost:8080/api
databaseUrl=jdbc:mysql://localhost:3306/mydb
javaRuntimeEnvironmentVersion