video_recording=true

video_output_directory=videos

save_record_on_failures=true
save_record_on_success=true


# Desktop recording is supported on Windows and Linux.
# On MacOS, only recording of the application window is supported.
# you can specify the recording area as either "desktop" or "application".
# If you choose "application", only the application window will be recorded, and if you
# choose "desktop", the entire desktop will be recorded.
# for example, if you want to record only chrome browser,
# you can set recording_area=application and then specify the application name
# as chrome in the application_name property.
# you can also specify the offset and size of the recording area.
# The offset is the distance from the top-left corner of the screen
# to the top-left corner of the recording area,
# and the size is the width and height of the recording area.
# For example, if you want to record a 1920x1080 area starting from the top-left
# corner of the screen, you can set offset_x=0, offset_y=0, and video_size=1920x1080.

offset_x = 0
offset_y = 0
video_size = 1920x1080
capture_mode=desktop
window_title="Google Chrome"
delete_if_test_passed=true
frame_rate=10

extension=.mp4