
# Waits configuration properties
polling_interval_millis=500
timeout_seconds=10

# Ignored Exceptions
ignored_exceptions=org.openqa.selenium.NoSuchElementException,\
                   org.openqa.selenium.StaleElementReferenceException,\
                   org.openqa.selenium.ElementClickInterceptedException

custom_timeout_message=Element was not found within the specified timeout.